In [8]:
# https://learnopencv.com/reading-and-writing-videos-using-opencv/
#load the video
import cv2
import numpy as np

# cap = cv2.VideoCapture('/mnt/DATA/Personnel/Other learning/Programming/Personal_projects/4_More_team_projects/6_SNN/3_data/testing_videos/9xg6B6d2Yts.mp4')
cap = cv2.VideoCapture('9xg6B6d2Yts.mp4')
 
if (cap.isOpened() == False):
    raise "Error opening the file"

# Read fps and frame count
else:   
    frameCount = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    frameWidth = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frameHeight = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

count, ret = 0, True

# buf = np.empty((frameCount, frameHeight, frameWidth, 3), np.dtype('uint8'))

while(count < frameCount and ret and cap.isOpened()):
    #dimensions of frameHeight x frameWidth x 3
    frame = np.zeros((frameHeight, frameWidth, 3), np.dtype('uint8'))
    ret, frame = cap.read()
    if ret:
        # cv2.imshow('Frame', frame)
        print(str(frame))
        f = open(f'frames/frame{count}.txt', "a")
        for row in frame:
            for column in row:
                f.write(str(column))
        f.close
        # np.savetxt(f'frames/frame{count}.txt', frame)



cap.release()
cv2.destroyAllWindows()

cv2.namedWindow('frame 10')
# cv2.imshow('frame 10', buf[9])

# cv2.waitKey(0)



[[[ 32  64  91]
  [ 32  64  91]
  [ 32  64  91]
  ...
  [ 93 135 167]
  [ 92 134 166]
  [ 92 134 166]]

 [[ 32  64  91]
  [ 32  64  91]
  [ 32  64  91]
  ...
  [ 93 135 167]
  [ 92 134 166]
  [ 92 134 166]]

 [[ 32  64  91]
  [ 32  64  91]
  [ 32  64  91]
  ...
  [ 93 135 167]
  [ 92 134 166]
  [ 92 134 166]]

 ...

 [[ 43  68  94]
  [ 43  68  94]
  [ 44  69  95]
  ...
  [ 68  97 125]
  [ 68  97 125]
  [ 65  94 122]]

 [[ 43  68  94]
  [ 43  68  94]
  [ 44  69  95]
  ...
  [ 68  97 125]
  [ 68  97 125]
  [ 65  94 122]]

 [[ 43  68  94]
  [ 43  68  94]
  [ 44  69  95]
  ...
  [ 65  94 122]
  [ 65  94 122]
  [ 68  97 125]]]
[[[ 32  64  91]
  [ 32  64  91]
  [ 32  64  91]
  ...
  [ 92 134 166]
  [ 92 134 166]
  [ 92 134 166]]

 [[ 32  64  91]
  [ 32  64  91]
  [ 32  64  91]
  ...
  [ 92 134 166]
  [ 92 134 166]
  [ 92 134 166]]

 [[ 32  64  91]
  [ 32  64  91]
  [ 32  64  91]
  ...
  [ 92 134 166]
  [ 92 134 166]
  [ 92 134 166]]

 ...

 [[ 43  68  94]
  [ 43  68  94]
  [ 44  69  95]
  ..